USE ecommerce_analysis;

-- ============================================================
-- E-COMMERCE SQL ANALYSIS
-- 06 - SALES ANALYSIS
-- ============================================================


-- Q1. Find the total revenue generated by the store
-- excluding cancelled orders

SELECT
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM Orders o
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled';


-- Q2. Find the total revenue generated by each order

SELECT
    o.order_id,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS order_total
FROM Orders o
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY o.order_id
ORDER BY order_total DESC;


-- Q3. Find the highest-value order

SELECT
    o.order_id,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS order_total
FROM Orders o
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY o.order_id
ORDER BY order_total DESC
LIMIT 1;


-- Q4. Find the average order value (AOV)

SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM (
    SELECT
        o.order_id,
        SUM(oi.quantity * oi.unit_price) AS order_total
    FROM Orders o
    JOIN Order_Items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status != 'Cancelled'
    GROUP BY o.order_id
) AS OrderTotals;


-- Q5. Find total revenue generated by each customer

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY c.customer_id, customer_name
ORDER BY total_revenue DESC;


-- Q6. Find total revenue generated by each product

SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM Products p
JOIN Order_Items oi
    ON p.product_id = oi.product_id
JOIN Orders o
    ON oi.order_id = o.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;


-- Q7. Find total revenue generated by each category

SELECT
    c.category_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM Categories c
JOIN Products p
    ON c.category_id = p.category_id
JOIN Order_Items oi
    ON p.product_id = oi.product_id
JOIN Orders o
    ON oi.order_id = o.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY c.category_id, c.category_name
ORDER BY total_revenue DESC;


-- Q8. Find monthly revenue

SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS monthly_revenue
FROM Orders o
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;


-- Q9. Find the number of completed/shipped orders for each month

SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(*) AS total_orders
FROM Orders
WHERE order_status != 'Cancelled'
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;


-- Q10. Find the month with the highest revenue

SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS monthly_revenue
FROM Orders o
JOIN Order_Items oi
    ON o.order_id = oi.order_id
WHERE o.order_status != 'Cancelled'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY monthly_revenue DESC
LIMIT 1;
